const ENTITY_TYPES = {
  PROJECT: "PROJECT",
  SPRINT: "SPRINT",
  TASK: "TASK",
  MEMBER: "MEMBER"
};

const ACTION_TYPES = {
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  ADDED: "ADDED",
  REMOVED: "REMOVED",
  STARTED: "STARTED",
  COMPLETED: "COMPLETED",
  STATUS_UPDATED: "STATUS_UPDATED"
};

module.exports = {
  ENTITY_TYPES,
  ACTION_TYPES
};
