const PROJECT_ROLES = {
  OWNER: "OWNER",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  DEVELOPER: "DEVELOPER",
  VIEWER: "VIEWER"
};

const PROJECT_ROLES_ARRAY = Object.values(PROJECT_ROLES);

module.exports = {
  PROJECT_ROLES,
  PROJECT_ROLES_ARRAY
};
